lexik_paybox_sample_call:
    path:     /payment/{account}
    defaults: { _controller: LexikPayboxBundle:Sample:index }
    requirements:
        account: \w+

lexik_paybox_sample_return:
    path:     /payment/{account}/return/{status}
    defaults: { _controller: LexikPayboxBundle:Sample:return, status: error }
    requirements:
        status: success|canceled|denied
