parameters:
    lexik_paybox.sample_response_listener.class: Lexik\Bundle\PayboxBundle\Listener\SampleIpnListener

services:
    lexik_paybox.sample_response_listener:
        class:     %lexik_paybox.sample_response_listener.class%
        arguments: [ %kernel.root_dir%, @filesystem ]
        tags:
            - { name: kernel.event_listener, event: paybox.ipn_response, method: onPayboxIpnResponse }
