language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
    exclude:
        # Since 4.0 Symfony requires PHP ^7.1.3
        - php: 5.5
          env: SYMFONY_VERSION=4.1.*
        - php: 5.6
          env: SYMFONY_VERSION=4.1.*
        - php: 7.0
          env: SYMFONY_VERSION=4.1.*
        - php: 5.5
          env: SYMFONY_VERSION=4.2.*
        - php: 5.6
          env: SYMFONY_VERSION=4.2.*
        - php: 7.0
          env: SYMFONY_VERSION=4.2.*

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.4.*
    - SYMFONY_VERSION=4.1.*
    - SYMFONY_VERSION=4.2.*

before_install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer require symfony/options-resolver:${SYMFONY_VERSION} --no-update

install: composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit
