language: php

matrix:
    fast_finish: true
    include:
        - php: 5.5
          env: SYMFONY_VERSION=2.7.*
        - php: 5.5
          env: SYMFONY_VERSION=2.8.*
        - php: 5.5
          env: SYMFONY_VERSION=3.4.*
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*
        - php: 7.2
          env: SYMFONY_VERSION=4.1.*
        - php: 7.2
          env: SYMFONY_VERSION=4.2.*
        - php: hhvm-stable
          sudo: required
          dist: trusty
          group: edge
    allow_failures:
        - php: hhvm-stable

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
    - composer require symfony/form:${SYMFONY_VERSION} --no-update
    - composer require symfony/options-resolver:${SYMFONY_VERSION} --no-update

install: composer install --prefer-dist --no-interaction

script: vendor/bin/phpunit
